Repository ousl-groupE5-ExpiryInspector/ExpiryInspector, pull requests merged in 2024-09, with the labels that each got.

#16 added basic UI components fixes #12
  Frontend/docs/README.md
  Frontend/srs/components/authImage.js
  Frontend/srs/components/authbutton.js
  Frontend/srs/components/background.js
  Frontend/srs/components/headertext.js
  Frontend/srs/components/inputField.js
  Frontend/srs/components/navigationBar.js
Labels: help wanted

#19 Navigation Added and javaScript files fixes #3
  Frontend/App.js
  Frontend/App.jsx
  Frontend/assets/Landing_image.jpg
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/components/authImage.js
  Frontend/src/components/authbutton.js
  Frontend/src/components/background.js
  Frontend/src/components/headertext.js
  Frontend/src/components/inputField.js
  Frontend/src/components/navigationBar.js
  Frontend/src/screens/Dashboard.js
  Frontend/src/screens/FogotPassword.js
  Frontend/src/screens/LandingPage.js
  Frontend/src/screens/LoginScreen.js
  Frontend/src/screens/SignInScreen.js
  Frontend/src/screens/UserAccount.js
  README.md
Labels: bug

#29 New Components added
  Frontend/src/components/BackgroundFlex.js
  Frontend/src/components/DescriptionText.js
  Frontend/src/components/HeaderWithIcon.js
  Frontend/src/components/LableText.js
  Frontend/src/components/NumberValue.js
  Frontend/src/components/Title2.js
  Frontend/src/components/Title3.js
  Frontend/src/components/TopBarButtons.js
Labels: enhancement

#41 Item details page created
  Frontend/assets/PlaceHolder_Item.jpg
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/components/HeaderWithIcon.js
  Frontend/src/screens/Dashboard.js
  Frontend/src/screens/FogotPassword.js
  Frontend/src/screens/ItemDetail.js
  Frontend/src/screens/ItemList.js
  Frontend/src/screens/UserAccount.js
Labels: Unit Code implement

#47 Basic UI Icons
  Frontend/assets/Add_icon.png
  Frontend/assets/BackArrow_icon.png
  Frontend/assets/Budget_Icon.png
  Frontend/assets/Delete_icon.png
  Frontend/assets/Edit_Icon.png
  Frontend/assets/Home_Icon.png
  Frontend/assets/Inventory_Icon.png
  Frontend/assets/List_Icon.png
  Frontend/assets/Next_icon.png
  Frontend/assets/Notification_Icon.png
  Frontend/assets/User_Icon.png
  Frontend/src/components/navigationBar.js
  Frontend/src/screens/ItemDetail.js
Labels: documentation

#52 Faq screen
  Frontend/App.js
  Frontend/src/components/navigationBar.js
  Frontend/src/screens/Camara.js
  Frontend/src/screens/Dashboard.js
  Frontend/src/screens/FAQ.js
  Frontend/src/screens/Notification.js
Labels: Unit Code implement

#57 App logo Update
  Frontend/android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  Frontend/android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  Frontend/android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  Frontend/android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  Frontend/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  Frontend/android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  Frontend/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  Frontend/android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  Frontend/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  Frontend/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  Frontend/android/app/src/main/res/values/strings.xml
  Frontend/assets/Round_logo.png
  Frontend/assets/square_logo.png
  Frontend/src/screens/FAQ.js
Labels: documentation

#58 added connection to FAQ page while in the landing page
  Frontend/assets/faqIcon.png
  Frontend/src/screens/LandingPage.js
Labels: Unit Code implement

#59 completed user account page
  Frontend/App.js
  Frontend/assets/userAccount.png
  Frontend/assets/userAccount_pic.png
  Frontend/src/screens/UserAccount.js
Labels: Unit Code implement

#56 Dashboard page completed please test and merge
  Frontend/App.js
  Frontend/assets/logo.png
  Frontend/src/components/HomeTopBar.js
  Frontend/src/screens/Dashboard.js
Labels: Unit Code implement
